server:
  port: 7003
spring:
  application:
    name: EVENT-SERVICE
  datasource:
    url: jdbc:postgresql://event-db:5432/event_db
    username: marius
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  cloud:
#    config:
#      uri: http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:7002/eureka
  instance:
    hostname: registry
