server:
  port: 7004
spring:
  application:
    name: BOOKING-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:9432/booking_db
    username: marius
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  cloud:
#    config:
#      uri: http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka
  instance:
    hostname: localhost
